
if [ ! -f ~/.linux_history ]; then
    ln -rsf ~/.linux/others/dotfiles/linux_history ~/.linux_history
fi

cat ~/.zsh_history | awk -F ';' '{print $2}' | sort | uniq >> ~/.linux_history
cat ~/.linux_history | sort | uniq > ~/.history
cat ~/.history > ~/.linux_history
rm ~/.history

export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

export LANG=en_US.UTF-8
export LC_CTYPE="en_US.utf8"
export LC_COLLATE="C"
export LC_MESSAGES="en_US.utf8"

# Oh my zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git gitfast git-extras github colorize tmux extract pandoc heroku)
source $ZSH/oh-my-zsh.sh

# Pyenv and Others Virtualenv support

function virtual_env_prompt () {
    REPLY=${VIRTUAL_ENV+(${VIRTUAL_ENV:t}) }
}

# add `|' to output redirections in the history
setopt histallowclobber

# try to avoid the 'zsh: no matches found...'
setopt nonomatch

# warning if file exists ('cat /dev/null > ~/.zshrc')
setopt NO_clobber

# don't warn me about bg processes when exiting
setopt nocheckjobs

# alert me if something failed
setopt printexitvalue

# with spelling correction, assume dvorak kb
setopt dvorak

# Allow comments even in interactive shells
setopt interactivecomments

# Use a default width of 80 for manpages for more convenient reading
export MANWIDTH=${MANWIDTH:-80}

# Color 256
export TERM='xterm-termite'

## pyenv
if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

if (( $+commands[pipenv] )); then
    eval "$(pipenv --completion)"
fi

if (( $+commands[pip] )); then
    eval "$(pip completion --zsh)"
fi

if (( $+commands[nvim] )); then
    export EDITOR=nvim
else
    export EDITOR=vi
fi

set -o vi

alias intelivix="cd $HOME/iury/intelivix"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
